version: 2
jobs:
  bucklescript-build-and-test:
    docker:
      - image: circleci/node:11

    environment:
      CI: true
      NODE_ENV: test

    working_directory: ~/repo/bs
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - run: npm test
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/bs/node_modules

  native-build-and-test:
    docker:
      - image: circleci/node:11
    environment:
      CI: true
    working_directory: ~/repo/native
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-native-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-native-dependencies-{{ .Branch }}-
            - v1-native-dependencies-
      - run: esy install
      - run: esy build
      - run: esy test
      - save_cache:
          key: v1-native-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.esy

workflows:
  version: 2
  build:
    jobs:
      - bucklescript-build-and-test
      - native-build-and-test
